language: node_js

node_js:
  - 8.9.1

sudo: false

cache:
  directories:
  - node_modules

before_script:
  - chmod +x -R /home/travis/build/ahmadarif/JasperNode/JasperStarter/bin

install:
  - npm install

script:
  - npm test